# Generated by Django 3.1.2 on 2020-11-01 12:57

import app.product.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20201029_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=app.product.models.product_image_url),
        ),
    ]
