# Generated by Django 3.1.2 on 2020-11-01 13:51

import app.product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20201101_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=11, upload_to=app.product.models.product_image_url),
            preserve_default=False,
        ),
    ]
