# Generated by Django 3.1.2 on 2020-11-25 21:06

import app.product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20201125_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app.product.models.product_image_url),
        ),
    ]
